version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(deps), dep-bot,"
    open-pull-requests-limit: 6
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(deps), dep-bot,"
    open-pull-requests-limit: 6
